local languages = require('localization.languages')

local lorem = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

function init(self)
	local font_hash = go.get("go#label", "font")
	languages.add_language('english', font_hash, lorem)
	print("LOADED ENGLISH")
end

function final(self)
	languages.remove_language('english')
end
