function init(self)
	-- profiler.enable(true)
	-- profiler.enable_ui(true)
	-- --profiler.set_ui_mode(profiler.VIEW_MODE_MINIMIZED)
	-- profiler.set_ui_mode(profiler.VIEW_MODE_FULL)

	-- 	msg.post(".", "acquire_input_focus")
	print("***************************************************")
	print("INIT!")
	self.first = true
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	if self.first then
		print("***************************************************")
		print("UPDATE!")
		self.first = false
	end
	
	-- draw a white line from (200, 200) to (200, 300)
	local color = vmath.vector4(255, 0.5, 0, 255)
	local x = 30
	local width = 250
	local start_pos = vmath.vector3(x, 0, 0.5)
	local end_pos = vmath.vector3(x, 1000, 0.5)
	msg.post("@render:", "draw_line", { start_point = start_pos, end_point = end_pos, color = color } )
	start_pos = vmath.vector3(x+width, 0, 0.5)
	end_pos = vmath.vector3(x+width, 1000, 0.5)
	msg.post("@render:", "draw_line", { start_point = start_pos, end_point = end_pos, color = color } )
end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	if action_id == nil then
		return
	end
	-- print("touch", action_id)
	-- sys.reboot()
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
